version: '3.7'
services:
  suricata:
    image: jasonish/suricata:6.0.4
    hostname: suricata
    container_name: suricata
    volumes:
      - ./etc:/etc/suricata
      - ./log:/var/log/suricata
      - ./rules:/var/lib/suricata/rules
    cap_add:
      # - ALL
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    environment:
      - TZ=Asia/Bangkok
    network_mode: host
    # command: /usr/bin/suricata -c /etc/suricata/suricata.yaml -s /var/lib/suricata/rules/exploitewithtag.rules -i eth0
    command: /usr/bin/suricata -c /etc/suricata/suricata.yaml -s /var/lib/suricata/rules/testrules.rules -i eth0
